//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class zq_CustomerTable
    {
        public int id { get; set; }

        [Required]
        [Display(Name = "姓名")]
        public string customerName { get; set; }

        [Required]
        [Phone]
        [RegularExpression(@"^1(3|4|5|7|8)\d{9}$", ErrorMessage = "请填写正确的电话")]
        [Display(Name = "电话号码")]
        public string customerPhone { get; set; }

        [Display(Name = "留言信息")]
        [StringLength(50, ErrorMessage = "最多只能输入50个字哦,请点击下方在线咨询")]
        public string customerMessage { get; set; }
    }
}
